import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TypekitLoader from "@/components/TypekitLoader";

const satoshi = localFont({
  src: "./fonts/Satoshi-Variable.ttf",
  variable: "--font-satoshi-variable",
  weight: "470 500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshi.variable}`}>
        {children}
        <TypekitLoader />
      </body>
    </html>
  );
}
